### ISSUE TITLE
Update UI

### ISSUE THREAD

**Issue by valentinperignon** [Infomaniak/ios-mail#285]
## General
- [x] **ThreadList**: update delete swipe action behavior (`role: .destructive`) (#314)
- [x] **ThreadList**: check if vertical padding of cells should be reduced

- [x] **ThreadList**: reduce section headers size according to Figma
- [x] **ThreadList+ThreadView**: _"(no subject)"_ should be written in italic - Changed on Figma: not italic anymore
- [x] **ThreadView**: increase divider height between messages (see Trello card)
<img width="363" alt="Capture d’écran 2022-09-02 à 08 06 59" src="https://user-images.githubusercontent.com/25110022/188069859-bf18d265-c978-47c3-8c5b-223062cb382d.png">

- [x] **MenuDrawer**: reduce the shadow in the header (#314)
- [x] **MenuDrawer**: reduce padding and size of icons (#314)
- [x] **MenuDrawer**: update quota (graph color and direction) (#314)
- [x] **Bottom toolbar**s: two colors for labels (icon/text) (#286)
- [x] **Bottom toolbars**: fix jumping behavior and iOS 16 (#314)
- [ ] **Bottom toolbars**: update toolbar with a smaller size for icons

## Dark Mode
- [x] **Editor**: Remove webView padding (#289)

**Comment by valentinperignon** [comment]
Done in several PRs
